[platformio]
default_environments = esp32_hub, esp8266_sniffer

[env:esp32_hub]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_src_filter = +<../src_hub/>

[env:esp8266_sniffer]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_src_filter = +<../src_wifi/>